Feature/IAR-4920
XenoHolographic-it/IAR-SDK-Sample-Android pull request #31
Opened 2022-02-02 14:17 UTC by lihongACY

# Overview

Add NFC-write screen and implement write NFC functionality

# Resources

https://iversoft.atlassian.net/browse/IAR-4920

# Technical Considerations

-

# Known Issues

-

# Testing Instructions

* Enter marker id in text field, click ‘Write Tag to NFC Device’ button, scan a NFC tag, to see if there is ‘Write NFC successfully” message and the correct marker id.
* Click ‘Randomize ID” button, the random generated Id should show in text field. Scan a NFC tag, to see if there is ‘Write NFC successfully” message and the correct marker id.

# Screenshots
![Screenshot_4920-1](https://user-images.githubusercontent.com/96147375/152170935-aa9d45e4-9e16-49a1-870c-aff5f822d301.jpg)
![Screenshot_4920-2](https://user-images.githubusercontent.com/96147375/152170994-9e979699-d83a-400a-a86e-473f67b766f3.jpg)

2022-02-02 14:59 UTC, MarkMurillo requested changes
I really like how you leverage the shared view model to communicate events from the activity to view model using livedata. This avoids any unnecessary interfaces and handles lifecycles beautifully. Just some minor changes and we're good

2022-02-02 14:59 UTC, MarkMurillo commented on surface-ar-sample/src/main/java/com/iar/surface_ar_sample/ui/fragments/nfc/WriteNFCFragment.kt
> +        currentActivity?.nfcViewModel?.nfcController?.observe(viewLifecycleOwner) { controller ->
You don't have to access the activity's viewmodel directly, you can actually leverage kotlin property delegate by declaring this as a property for this fragment:
`private val nfcViewModel by activityViewModels<NFCViewModel>()`
This will actually be the same instance declared in the MainActivity (the parent activity) since you also used kotlin delegates to instantiate it on the activity.

2022-02-02 14:59 UTC, MarkMurillo commented on surface-ar-sample/src/main/java/com/iar/surface_ar_sample/ui/fragments/nfc/WriteNFCFragment.kt
> +        currentActivity?.nfcViewModel?.nfcController?.observe(viewLifecycleOwner) { controller ->
You could test this by creating a property ID in the view model that's set to 0. Set it in the activity to 19 and then get the same view model in the fragment by property delegate and check the id. It will be the same as what you set it in the activity.

2022-02-03 15:19 UTC, lihongACY commented on surface-ar-sample/src/main/java/com/iar/surface_ar_sample/ui/fragments/nfc/WriteNFCFragment.kt
> +        currentActivity?.nfcViewModel?.nfcController?.observe(viewLifecycleOwner) { controller ->
Good point.

2022-02-03 17:18 UTC, MarkMurillo approved these changes

2022-02-03 18:33 UTC, merged